### PR TITLE
Czech i18n added

### PR DESCRIPTION
**Pull request by svetlemodry**

### CODE REVIEW

**Comment by VincentTam** [comment]
Please be aware of issue https://github.com/gohugoio/hugo/issues/3846#issuecomment-325635813.  There're missing [pluralisation rules](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html) for `few` and `many`.

**Comment by svetlemodry** [comment]
Hey @orianna-zzo, are you still around?
It would be pity to have this nice hugo template die.
Do you by any chance plan to look into reviewing the pull requests and issues, or are there other priorities on you list and no time for the AllinOne?
Cheers!

**Comment by EliiseS** [comment]
@svetlemodry I've started maintaining this theme in a new repo, found here: https://github.com/EliiseS/AllinOne

**Comment by svetlemodry** [comment]
> @svetlemodry I've started maintaining this theme in a new repo, found here: https://github.com/EliiseS/AllinOne

@EliiseS Awesome, thanks for taking the time!

**Pull request closed without merging**
